# Generated by Django 5.1.2 on 2024-12-06 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alien",
            fields=[
                (
                    "alienid",
                    models.AutoField(
                        db_column="alienId", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=35)),
                ("email", models.CharField(max_length=25)),
            ],
            options={
                "db_table": "alien",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "commentid",
                    models.AutoField(
                        db_column="commentId", primary_key=True, serialize=False
                    ),
                ),
                ("text", models.CharField(blank=True, max_length=1500, null=True)),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("believability", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "comment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Expedition",
            fields=[
                (
                    "expeditionid",
                    models.AutoField(
                        db_column="expeditionId", primary_key=True, serialize=False
                    ),
                ),
                (
                    "craftmodel",
                    models.CharField(
                        blank=True, db_column="craftModel", max_length=35, null=True
                    ),
                ),
                ("duration", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "expedition",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Governmentemployee",
            fields=[
                (
                    "employeeid",
                    models.AutoField(
                        db_column="employeeId", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=35, null=True)),
                ("country", models.CharField(blank=True, max_length=25, null=True)),
                ("position", models.CharField(blank=True, max_length=35, null=True)),
            ],
            options={
                "db_table": "governmentemployee",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Governmentnote",
            fields=[
                (
                    "noteid",
                    models.AutoField(
                        db_column="noteId", primary_key=True, serialize=False
                    ),
                ),
                ("text", models.CharField(blank=True, max_length=500, null=True)),
                ("date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "governmentnote",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Sighting",
            fields=[
                (
                    "sightingid",
                    models.AutoField(
                        db_column="sightingId", primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("comments", models.CharField(blank=True, max_length=1500, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=25, null=True)),
                ("shape", models.CharField(blank=True, max_length=25, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("duration", models.IntegerField(blank=True, null=True)),
                (
                    "dateposted",
                    models.DateTimeField(blank=True, db_column="datePosted", null=True),
                ),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "sighting",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Alientoexpedition",
            fields=[
                (
                    "alienid",
                    models.OneToOneField(
                        db_column="alienId",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="aliens_app.alien",
                    ),
                ),
            ],
            options={
                "db_table": "alientoexpedition",
                "managed": False,
            },
        ),
    ]
