# Generated by Django 5.1.1 on 2024-11-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GovernmentEmployee",
            fields=[
                ("employeeId", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=35)),
                ("country", models.CharField(max_length=25)),
                ("position", models.CharField(max_length=35)),
            ],
        ),
    ]
