# Generated by Django 5.1.1 on 2024-11-16 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aliens_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alien",
            fields=[
                (
                    "alienid",
                    models.IntegerField(
                        db_column="alienId", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=35)),
                ("email", models.CharField(max_length=25)),
            ],
            options={
                "db_table": "alien",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.IntegerField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.IntegerField()),
                ("is_active", models.IntegerField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "commentid",
                    models.IntegerField(
                        db_column="commentId", primary_key=True, serialize=False
                    ),
                ),
                ("text", models.CharField(blank=True, max_length=500, null=True)),
                ("date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "comment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.PositiveSmallIntegerField()),
                ("change_message", models.TextField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Expedition",
            fields=[
                (
                    "expeditionid",
                    models.IntegerField(
                        db_column="expeditionId", primary_key=True, serialize=False
                    ),
                ),
                (
                    "craftmodel",
                    models.CharField(
                        blank=True, db_column="craftModel", max_length=35, null=True
                    ),
                ),
                ("duration", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "expedition",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Governmentnote",
            fields=[
                (
                    "noteid",
                    models.IntegerField(
                        db_column="noteId", primary_key=True, serialize=False
                    ),
                ),
                ("text", models.CharField(blank=True, max_length=500, null=True)),
                ("date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "governmentnote",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Sighting",
            fields=[
                (
                    "sightingid",
                    models.IntegerField(
                        db_column="sightingId", primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=25, null=True)),
                ("state", models.CharField(blank=True, max_length=25, null=True)),
                ("shape", models.CharField(blank=True, max_length=25, null=True)),
                ("duration", models.IntegerField(blank=True, null=True)),
                (
                    "dateposted",
                    models.DateTimeField(blank=True, db_column="datePosted", null=True),
                ),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "sighting",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "userid",
                    models.IntegerField(
                        db_column="userId", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=25, null=True)),
                ("email", models.CharField(blank=True, max_length=35, null=True)),
                (
                    "datejoined",
                    models.DateTimeField(blank=True, db_column="dateJoined", null=True),
                ),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="governmentemployee",
            options={"managed": False},
        ),
        migrations.CreateModel(
            name="Alientoexpedition",
            fields=[
                (
                    "alienid",
                    models.OneToOneField(
                        db_column="alienId",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="aliens_app.alien",
                    ),
                ),
            ],
            options={
                "db_table": "alientoexpedition",
                "managed": False,
            },
        ),
    ]
